ConnectHolland\PiccoloContentBundle\Document\StandardPage:
    properties:
        name:
            - NotBlank: ~
            - ConnectHolland\PiccoloContentBundle\Validator\Constraints\ContainsAlphanumeric: ~